export default {
    OPEN_TAB_WEEK_MONTH: 'OPEN_TAB_WEEK_MONTH',

    ACTIVE_MONTH_SWITCH: 'ACTIVE_MONTH_SWITCH',

    CHANGE_NEXT_MONTH: 'CHANGE_NEXT_MONTH',
    CHANGE_PREW_MONTH: 'CHANGE_PREW_MONTH',

    CHANGE_ACTIVE_DAY: 'CHANGE_ACTIVE_DAY',

    LOGIN: 'LOGIN',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_RESPONS: 'LOGIN_RESPONS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    
}